### ISSUE TITLE
ValueError: 'icg_benchmark/third_party/libmcubes/mcubes.pyx' doesn't match any files

### ISSUE THREAD

**Issue by ubless607** [renezurbruegg/icg_benchmark#1]
When I run `python setup.py build_ext --inplace`, it gives this error.
`ValueError: 'icg_benchmark/third_party/libmcubes/mcubes.pyx' doesn't match any files`

**Comment by renezurbruegg** [comment]
Thanks for pointing this out. It looks like some files did not get synced, probably due to the .gitignore.

I have disabled the setup.py script for now, and the installation should work now.

**Comment by ubless607** [comment]
@renezurbruegg Thank you!
