### ISSUE TITLE
ModuleNotFoundError: No module named 'icg_net.model.mask3d'

### ISSUE THREAD

**Issue by Jinbo-Zuo** [renezurbruegg/icg_benchmark#6]
When I run "python scripts/test_icgnet.py --scene packed --object-set packed/test" as your Readme, I got the error "ModuleNotFoundError: No module named 'icg_net.model.mask3d' ". After checking, there is indeed no "mask3d" in the "icg_net.model" directory.

**Comment by renezurbruegg** [comment]
Can you quickly checkout the fix/installation branch and see if this works for you? 
``` git checkout fix/installation ```

It runs fine like this for me locally, but I had it happen before that the .gitignore removed some important files, so let me know if you still experience issues

**Comment by Jinbo-Zuo** [comment]
It should not be because the file was removed, because I did not find "icg_net/model/mask3d" in your github page, as shown in the attachment. And I searched the entire project and didn't find "mask3d" anywhere.





At 2024-09-09 19:14:38, "renezurbruegg" ***@***.***> wrote:

Can you quickly checkout the fix/installation branch and see if this works for you?
git checkout fix/installation

It runs fine like this for me locally, but I had it happen before that the .gitignore removed some important files, so let me know if you still experience issues

**Comment by renezurbruegg** [comment]
Can you give me a stack trace or something? 
I can't find the line `from icg_net.model import mask3d` anywhere in the codebase.

**Comment by Jinbo-Zuo** [comment]
Actually, it is in config.yaml, the path is "icg_benchmark/data/51--0.656/config.yaml", as shown in the figure:
![20240910-140605](https://github.com/user-attachments/assets/786caf42-1823-402a-8eb7-3f670080f95f)

**Comment by renezurbruegg** [comment]
Can you try downloading the checkpoints again? I updated the config. 
Here is the link (also gets pulled from the download script): https://drive.google.com/file/d/1RzdhOBX5GV42qbvmjuL31Nf1N90gT-ra/view?usp=drive_link

**Comment by Jinbo-Zuo** [comment]
Thanks for your timely reply. After changing “config.yaml”, the code ran successfully. It is worth mentioning that some places in yaml and code that use absolute paths need to be modified by users to their own paths, "/home/rene/ICRA_2024/icg_benchmark/data/51--0.656/checkpoint.ckpt"
